packages:
  - .

autoInstallPeers: false
blockExoticSubdeps: false

allowBuilds:
  dsh-as-a-verifier@https://codeload.github.com/omdsh-dev/dsh-as-a-verifier/tar.gz/359c41e6f3882c720c1d41f79d4f3ed6cb7d05f5: true
  esbuild: true
